############################################################################
# Create Recovery Partition
# Generated by PoshForge — https://jimtyler.org/gui
############################################################################

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

[System.Windows.Forms.Application]::EnableVisualStyles()
[System.Windows.Forms.Application]::SetCompatibleTextRenderingDefault($false)
# ---- Functions ----
function vyrblLocal-zasifrovatDisk {
    #Write-Host 'Zapinam bitLocker.' -ForegroundColor red -BackgroundColor yellow
    #( ( Get-Date -Format 'yyyy-MM-dd HH:mm:ss' ) + ' Zapinam bitlocker.' ) | Out-File $logFile -Append -Encoding ascii
    Enable-BitLocker -MountPoint c: -RecoveryPasswordProtector -UsedSpaceOnly
    #return 'restartuj'
}

function vyrblLocal-desifrovatDisk {
    #Write-Host 'Vypinam bitLocker.' -ForegroundColor blue -BackgroundColor yellow
    #( ( Get-Date -Format 'yyyy-MM-dd HH:mm:ss' ) + ' Vypinam bitlocker.' ) | Out-File $logFile -Append -Encoding ascii
    Disable-BitLocker -MountPoint c:
}

function vyrblLocal-beziDesifrovani {
    return 100 - ( Get-BitLockerVolume -MountPoint c: ).EncryptionPercentage
}

function vyrblLocal-vytvoritRecoveryPartition {
    #Write-Host 'Vytvarim recovery partition.' -ForegroundColor red -BackgroundColor yellow
    #( ( Get-Date -Format 'yyyy-MM-dd HH:mm:ss' ) + ' Vytvarim recovery partition.' ) | Out-File $logFile -Append -Encoding ascii

    $newSize = ( Get-Partition -DriveLetter C ).Size - 1073741824 # zmenseni o 1 GB
    if( $newSize -gt ( Get-PartitionSupportedSize -DriveLetter C ).SizeMin ){

        Resize-Partition -DriveLetter C -Size $newSize
        $diskNumber = ( Get-Partition |? { $_.DriveLetter -eq 'C' } ).DiskNumber
        New-Partition -DiskNumber $diskNumber -UseMaximumSize -GptType "{de94bba4-06d1-4d40-a16a-bfd50179d6ac}"

        # Re-enable Windows Recovery Environment
        reagentc /enable

    }else{
        Write-Host 'Sem se recovery partition nevejde.' -ForegroundColor red -BackgroundColor yellow
    }
}

function fvLocalMain {
    $winreFileName = 'Winre.wim'
    #$winreFilePath = '\\dmczfsisd01.dmcz.emea.denso\install\_MS\MS_Windows\MS_W10\Recovery'
    $winreFilePath = $PSScriptRoot
    $winreSource = $winreFilePath + '\' + $winreFileName
    $winreDestinationFolder = 'C:\Windows\System32\Recovery\'
    $winreDestinationFile = $winreDestinationFolder + $winreFileName
    if( ( ( Get-Partition |? { $_.Type -eq 'Recovery' } | Measure-Object ).Count ) -eq 0 ){
    # neni recovery partition
    if( -not ( Test-Path -Path $winreDestinationFile ) ){
        if( -not (Test-Path -Path $winreSource)){
            $State.Text = "Winre.wim nenalezen dejte do adresare scriptu"
        }else{
            # chybi soubor Winre.wim
            $State.Text = "Kopiruji Winre.wim"
            #New-PSDrive -Name source -PSProvider FileSystem -Root $winreFilePath -Credential ( Get-Credential )
            Copy-Item -Path $winreSource -Destination $winreDestinationFolder
            #Remove-PSDrive source
        }
    }else{
        Write-Host 'Soubor Winre.wim je pritomen.' -ForegroundColor red -BackgroundColor yellow
        
    }
    }
        if( ( Get-Partition |? { $_.Type -eq 'Recovery' } | Measure-Object ).Count -eq 0 ){

        # neni recovery partition
        
        

        if( ( ( Get-BitLockerVolume -MountPoint c: ).VolumeStatus ) -eq 'FullyEncrypted' ){

            # je zasifrovano => desifrovat
            $State.Text = "Desifruji BitLocker"
            vyrblLocal-desifrovatDisk

            # cekani az bude desifrovano
            vyrblLocal-cekaniDesifrovani

            $State.Text = "Vytvarim Recovery Partition"
            # vytvoreni recovery partition
            vyrblLocal-vytvoritRecoveryPartition
            vyrblLocal-cekaniPartition

        }
        elseif( ( ( Get-BitLockerVolume -MountPoint c: ).VolumeStatus ) -eq 'FullyDecrypted' ){
            $State.Text = "Vytvarim Recovery Partition"
            # vytvoreni recovery partition
            vyrblLocal-vytvoritRecoveryPartition
            vyrblLocal-cekaniPartition
            # cekani
            

            # zasifrovat disk
            #$return = vyrblLocal-zasifrovatDisk

        }else{
            $State.Text = "Desifruji BitLocker"
            vyrblLocal-zasifrovatDisk
            vyrblLocal-desifrovatDisk

            $State.Text = "Vytvarim Recovery Partition"
            # vytvoreni recovery partition
            vyrblLocal-vytvoritRecoveryPartition
            vyrblLocal-cekaniPartition
        }
        

    }else{

        # je recovery partition
        
        

        if( ( ( Get-BitLockerVolume -MountPoint c: ).VolumeStatus ) -eq 'FullyDecrypted' ){

            # je odsifrovano => zasifrovat
            #$return = vyrblLocal-zasifrovatDisk

        }
        elseif( ( ( Get-BitLockerVolume -MountPoint c: ).VolumeStatus ) -eq 'EncryptionInProgress' ){

            # cekani az bude zasifrovano
            $State.Text = "Desifruji BitLocker"
            vyrblLocal-cekaniSifrovani
            vyrblLocal-desifrovatDisk
            vyrblLocal-cekaniDesifrovani

        }
        elseif( ( ( Get-BitLockerVolume -MountPoint c: ).VolumeStatus ) -eq 'FullyEncrypted' ){
            $State.Text = "Desifruji BitLocker"
            vyrblLocal-desifrovatDisk
            vyrblLocal-cekaniDesifrovani
        }
    }

    
}

function vyrblLocal-cekaniPartition {
    do{
        Start-Sleep -Milliseconds 100
    }while( ( Get-Partition |? { $_.Type -eq 'Recovery' } | Measure-Object ).Count -eq 0 )
    
    
}

function vyrblLocal-cekaniDesifrovani {
    do{
        Start-Sleep -Seconds 1
        $progressBar2.Value = vyrblLocal-beziDesifrovani
    }while( ( ( Get-BitLockerVolume -MountPoint c: ).VolumeStatus ) -ne 'FullyDecrypted' )
    
}

function vyrblLocal-cekaniSifrovani {
    do{
        Start-Sleep -Seconds 1
        $progressBar2.Value = vyrblLocal-beziDesifrovani
    }while( ( ( Get-BitLockerVolume -MountPoint c: ).VolumeStatus ) -ne 'FullyEncrypted' )
    
}

function fvLocal-cekaniComplete {
    do{
        Start-Sleep -Milliseconds 100
        
    }while($running)
    $State.Text = "Hotovo"
}
# ---- State Machine ----
$running = $false
# ---- Form ----
$form = New-Object System.Windows.Forms.Form
$form.Text = 'Create Recovery Partition'
$form.BackColor = [System.Drawing.Color]::FromArgb(10, 214, 255)
$form.ClientSize = New-Object System.Drawing.Size(460, 300)

# ---- label3 (Label) ----
$label3 = New-Object System.Windows.Forms.Label
$label3.Text = 'Progress'
$label3.Location = New-Object System.Drawing.Point(24, 8)
$label3.Size = New-Object System.Drawing.Size(100, 23)
$label3.Name = 'label3'
$form.Controls.Add($label3)

# ---- progressBar2 (ProgressBar) ----
$progressBar2 = New-Object System.Windows.Forms.ProgressBar
$progressBar2.Minimum = 0
$progressBar2.Maximum = 100
$progressBar2.Location = New-Object System.Drawing.Point(24, 40)
$progressBar2.Size = New-Object System.Drawing.Size(408, 24)
$progressBar2.Name = 'progressBar2'
$form.Controls.Add($progressBar2)

# ---- AbortBtn (Button) ----
$AbortBtn = New-Object System.Windows.Forms.Button
$AbortBtn.Text = 'Create recovery partition'
$AbortBtn.Location = New-Object System.Drawing.Point(24, 80)
$AbortBtn.Size = New-Object System.Drawing.Size(90, 28)
$AbortBtn.Name = 'AbortBtn'
$form.Controls.Add($AbortBtn)

# ---- State (Label) ----
$State = New-Object System.Windows.Forms.Label
$State.Text = 'Label'
$State.Location = New-Object System.Drawing.Point(88, 8)
$State.Size = New-Object System.Drawing.Size(100, 23)
$State.Name = 'State'
$form.Controls.Add($State)

# ---- Event handlers ----
$AbortBtn.Add_Click({
    if($running){
        exit
    }else{
        $running = $true
        fvLocalMain
    }
})

# ---- Show the form ----
[void]$form.ShowDialog()
$form.Dispose()