############################################################################
# Check Completition
# Generated by PoshForge — https://jimtyler.org/gui
############################################################################

Add-Type -AssemblyName System.Windows.Forms
Add-Type -AssemblyName System.Drawing

[System.Windows.Forms.Application]::EnableVisualStyles()
[System.Windows.Forms.Application]::SetCompatibleTextRenderingDefault($false)

# ---- Form ----
$form = New-Object System.Windows.Forms.Form
$form.Text = 'Check Completition'
$form.FormBorderStyle = [System.Windows.Forms.FormBorderStyle]::SizableToolWindow
$form.BackColor = [System.Drawing.Color]::FromArgb(122, 228, 255)
$form.ClientSize = New-Object System.Drawing.Size(480, 320)

# ---- label1 (Label) ----
$label1 = New-Object System.Windows.Forms.Label
$label1.Text = 'Ram'
$label1.Location = New-Object System.Drawing.Point(32, 16)
$label1.Size = New-Object System.Drawing.Size(100, 23)
$label1.Name = 'label1'
$form.Controls.Add($label1)

# ---- RAMBUTTON (Button) ----
$RAMBUTTON = New-Object System.Windows.Forms.Button
$RAMBUTTON.Text = '16GB ok'
$RAMBUTTON.ForeColor = [System.Drawing.Color]::FromArgb(0, 0, 0)
$RAMBUTTON.BackColor = [System.Drawing.Color]::FromArgb(0, 255, 30)
$RAMBUTTON.Enabled = $false
$RAMBUTTON.Location = New-Object System.Drawing.Point(32, 40)
$RAMBUTTON.Size = New-Object System.Drawing.Size(80, 32)
$RAMBUTTON.Name = 'RAMBUTTON'
$form.Controls.Add($RAMBUTTON)

# ---- label2 (Label) ----
$label2 = New-Object System.Windows.Forms.Label
$label2.Text = 'saturnin and Local Users'
$label2.Location = New-Object System.Drawing.Point(32, 80)
$label2.Size = New-Object System.Drawing.Size(136, 24)
$label2.Name = 'label2'
$form.Controls.Add($label2)

# ---- saturninButton (Button) ----
$saturninButton = New-Object System.Windows.Forms.Button
$saturninButton.Text = 'FIX NOW'
$saturninButton.BackColor = [System.Drawing.Color]::FromArgb(255, 0, 0)
$saturninButton.Location = New-Object System.Drawing.Point(32, 104)
$saturninButton.Size = New-Object System.Drawing.Size(90, 28)
$saturninButton.Name = 'saturninButton'
$form.Controls.Add($saturninButton)

# ---- label3 (Label) ----
$label3 = New-Object System.Windows.Forms.Label
$label3.Text = 'Recovery partition'
$label3.Location = New-Object System.Drawing.Point(32, 144)
$label3.Size = New-Object System.Drawing.Size(100, 23)
$label3.Name = 'label3'
$form.Controls.Add($label3)

# ---- RecoveryButton (Button) ----
$RecoveryButton = New-Object System.Windows.Forms.Button
$RecoveryButton.Text = 'FIX NOW'
$RecoveryButton.Location = New-Object System.Drawing.Point(32, 168)
$RecoveryButton.Size = New-Object System.Drawing.Size(90, 28)
$RecoveryButton.Name = 'RecoveryButton'
$form.Controls.Add($RecoveryButton)

# ---- Event handlers ----
$saturninButton.Add_Click({
    # TODO: saturninButton.Click
})

$RecoveryButton.Add_Click({
    # TODO: RecoveryButton.Click
})

# ---- Show the form ----
[void]$form.ShowDialog()
$form.Dispose()
